export const PERMISSIONS = {
  // Vendor permissions
  VENDOR_CREATE: 'vendor:create',
  VENDOR_READ: 'vendor:read',
  VENDOR_UPDATE: 'vendor:update',
  VENDOR_DELETE: 'vendor:delete',
  VENDOR_SUBMIT: 'vendor:submit',
  VENDOR_APPROVE: 'vendor:approve',
  VENDOR_REJECT: 'vendor:reject',
  VENDOR_TERMINATE: 'vendor:terminate',
  VENDOR_RESUBMIT: 'vendor:resubmit',

  // Compliance permissions
  COMPLIANCE_TEMPLATE_CREATE: 'compliance:template:create',
  COMPLIANCE_TEMPLATE_READ: 'compliance:template:read',
  COMPLIANCE_TEMPLATE_UPDATE: 'compliance:template:update',
  COMPLIANCE_TEMPLATE_DELETE: 'compliance:template:delete',
  COMPLIANCE_ASSIGN: 'compliance:assign',
  COMPLIANCE_UPDATE: 'compliance:update',
  COMPLIANCE_READ: 'compliance:read',

  // Document permissions
  DOCUMENT_UPLOAD: 'document:upload',
  DOCUMENT_READ: 'document:read',
  DOCUMENT_DELETE: 'document:delete',
  DOCUMENT_VERIFY: 'document:verify',

  // Workflow permissions
  WORKFLOW_CONFIG_CREATE: 'workflow:config:create',
  WORKFLOW_CONFIG_READ: 'workflow:config:read',
  WORKFLOW_CONFIG_UPDATE: 'workflow:config:update',
  WORKFLOW_APPROVE: 'workflow:approve',
  WORKFLOW_REJECT: 'workflow:reject',
  WORKFLOW_DELEGATE: 'workflow:delegate',
  WORKFLOW_ESCALATE: 'workflow:escalate',

  // User permissions
  USER_CREATE: 'user:create',
  USER_READ: 'user:read',
  USER_UPDATE: 'user:update',
  USER_DELETE: 'user:delete',
  USER_ROLE_ASSIGN: 'user:role:assign',

  // Role permissions
  ROLE_CREATE: 'role:create',
  ROLE_READ: 'role:read',
  ROLE_UPDATE: 'role:update',
  ROLE_DELETE: 'role:delete',

  // Audit permissions
  AUDIT_READ_FULL: 'audit:read:full',
  AUDIT_READ_RESTRICTED: 'audit:read:restricted',
  AUDIT_EXPORT: 'audit:export',
  AUDIT_VERIFY: 'audit:verify',

  // Report permissions
  REPORT_COMPLIANCE: 'report:compliance',
  REPORT_VENDOR: 'report:vendor',
  REPORT_AUDIT: 'report:audit',
  REPORT_EXPORT: 'report:export',

  // Admin permissions
  ADMIN_SYSTEM_CONFIG: 'admin:system:config',
  ADMIN_IMPORT: 'admin:import',
  ADMIN_EXPORT: 'admin:export',
} as const;

export type Permission = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLES = {
  ADMIN: 'ADMIN',
  COMPLIANCE_OFFICER: 'COMPLIANCE_OFFICER',
  PROCUREMENT_MANAGER: 'PROCUREMENT_MANAGER',
  FINANCE_REVIEWER: 'FINANCE_REVIEWER',
  AUDITOR: 'AUDITOR',
  VENDOR_PORTAL_USER: 'VENDOR_PORTAL_USER',
  VIEWER: 'VIEWER',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const ROLE_PERMISSIONS: Record<Role, Permission[]> = {
  [ROLES.ADMIN]: Object.values(PERMISSIONS),

  [ROLES.COMPLIANCE_OFFICER]: [
    PERMISSIONS.VENDOR_READ,
    PERMISSIONS.VENDOR_UPDATE,
    PERMISSIONS.VENDOR_SUBMIT,
    PERMISSIONS.COMPLIANCE_TEMPLATE_CREATE,
    PERMISSIONS.COMPLIANCE_TEMPLATE_READ,
    PERMISSIONS.COMPLIANCE_TEMPLATE_UPDATE,
    PERMISSIONS.COMPLIANCE_ASSIGN,
    PERMISSIONS.COMPLIANCE_UPDATE,
    PERMISSIONS.COMPLIANCE_READ,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_VERIFY,
    PERMISSIONS.WORKFLOW_APPROVE,
    PERMISSIONS.WORKFLOW_REJECT,
    PERMISSIONS.AUDIT_READ_RESTRICTED,
    PERMISSIONS.REPORT_COMPLIANCE,
    PERMISSIONS.REPORT_VENDOR,
  ],

  [ROLES.PROCUREMENT_MANAGER]: [
    PERMISSIONS.VENDOR_CREATE,
    PERMISSIONS.VENDOR_READ,
    PERMISSIONS.VENDOR_UPDATE,
    PERMISSIONS.VENDOR_SUBMIT,
    PERMISSIONS.VENDOR_APPROVE,
    PERMISSIONS.VENDOR_REJECT,
    PERMISSIONS.COMPLIANCE_READ,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.WORKFLOW_APPROVE,
    PERMISSIONS.WORKFLOW_REJECT,
    PERMISSIONS.WORKFLOW_DELEGATE,
    PERMISSIONS.REPORT_VENDOR,
  ],

  [ROLES.FINANCE_REVIEWER]: [
    PERMISSIONS.VENDOR_READ,
    PERMISSIONS.COMPLIANCE_READ,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.DOCUMENT_VERIFY,
    PERMISSIONS.WORKFLOW_APPROVE,
    PERMISSIONS.WORKFLOW_REJECT,
    PERMISSIONS.REPORT_VENDOR,
  ],

  [ROLES.AUDITOR]: [
    PERMISSIONS.VENDOR_READ,
    PERMISSIONS.COMPLIANCE_READ,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.AUDIT_READ_FULL,
    PERMISSIONS.AUDIT_EXPORT,
    PERMISSIONS.AUDIT_VERIFY,
    PERMISSIONS.REPORT_COMPLIANCE,
    PERMISSIONS.REPORT_VENDOR,
    PERMISSIONS.REPORT_AUDIT,
  ],

  [ROLES.VENDOR_PORTAL_USER]: [
    PERMISSIONS.VENDOR_READ,
    PERMISSIONS.VENDOR_UPDATE,
    PERMISSIONS.VENDOR_RESUBMIT,
    PERMISSIONS.DOCUMENT_UPLOAD,
    PERMISSIONS.DOCUMENT_READ,
    PERMISSIONS.COMPLIANCE_READ,
  ],

  [ROLES.VIEWER]: [
    PERMISSIONS.VENDOR_READ,
    PERMISSIONS.COMPLIANCE_READ,
    PERMISSIONS.DOCUMENT_READ,
  ],
};
